### ISSUE TITLE
Docker compose is wrong.

### ISSUE THREAD

**Issue by Protektor-Desura** [cabernetwork/cabernet#18]
The [docker-compose.yml](https://github.com/cabernetwork/cabernet/blob/master/docker-compose.yml) is wrong and doesn't even pull the correct docker image for this project. I recommend you post a docker-compose.yml like this. 

```
version: "3.1"
services:
  cabernet:
    container_name: cabernet
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=America/Chicago
    image: ghcr.io/cabernetwork/cabernet:latest
    ports:
      - "5004:5004"    # Port used to stream
      - "6077:6077"    # Web Interface Port
      - "65001:65001"  # HDHomeRun Port 
    restart: unless-stopped
    volumes:
      - /home/docker/cabernet:/app/data/
```

I would recommend you look at using linuxserver ubuntu as the base so you can get the ability to pick the user the docker runs as.
