### ISSUE TITLE
Docker instructions are NOT working for cabernet, please help.

### ISSUE THREAD

**Issue by Nostradamus1973** [cabernetwork/cabernet#60]
Good morning Everyone,

I'm new to docker(and loving it), however, I'm having a terrible time trying to get this working in Portainer or as a docker itself.

Can someone please help  me?
I'm running Kubuntu 22.10 as an OS.

I really think this script could be amazing giving its' feature set, unfortunately the Docker instructions make little to no sense to me and I can't get Cabernet installed.

Thank you and have a nice day.

**Comment by rocky4546** [comment]
First I am not an expert on Docker.  I did get it running and tested, but I rely on others to let me know when it has an issue.  That being said, I am running Ubuntu 20 and find it simple to run either in MS Windows or Linux as a service rather than a Docker.  If you want to see the work we did on Docker, it is located here before moving to Cabernet.  That may help.
https://github.com/rocky4546/tvheadend-locast/issues/6
The file most people use is Dockerfile_tvh_crypt.alpine. Also, we do push updates on each commit to 
http://ghcr.io/cabernetwork/cabernet:latest
so it should have the latest version.  If you are interested in setting up Cabernet as a service, let me know.

**Comment by cookieisland** [comment]
I am using docker on Ubuntu 18.04.6 LTS. I do not use the docker image on ghcr.io because it does not contain the tvguide EPG provider.  

What I do is clone the repos for cabernet and the tvguide epg from github. Here are the two github repos and the location I clone them to:
https://github.com/cabernetwork/cabernet  which I clone to /home/cookieisland/source/cabernet
https://github.com/cabernetwork/provider_epg_tvguide which I clone to /home/cookieisland/source/provider_epg_tvguide

I then created a location to save the cabernet data directory and a file for the crypt key. In my case I create /home/cookieisland/docker/cabernet/config/data for my cabernet data directory and an empty file named /home/cookieisland/docker/cabernet/config/key.txt for the crypt key.

Then I use the following in my docker-compose.yaml file:
```
cabernet:
    build:
      context: /home/cookieisland/source/cabernet
      dockerfile: Dockerfile_tvh_crypt.alpine
    image: cabernet
    container_name: cabernet
    network_mode: host
    environment:
      - TZ="America/Los_Angeles"
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    cpu_shares: 2048
    restart: unless-stopped
    volumes:
      - /home/cookieisland/docker/cabernet/config/data:/app/data
      - /home/cookieisland/docker/cabernet/config/key.txt:/root/.cabernet/key.txt
```

I also have an automated BASH script that updates the docker image whenever I want to pull the latest cabernet and tvguide images. It ensure cabernet and tvguide are up to date and copies the correct tvguide subdirectory into the cabernet plugins_ext directory. The script looks like this:
```
#!/bin/bash
cd /home/cookieisland/source/provider_epg_tvguide
git pull
cd /home/cookieisland/source/cabernet
git pull
cp -ruv --preserve /home/cookieisland/source/provider_epg_tvguide/provider_epg_tvguide plugins_ext
cd /home/cookieisland/compose/htpc
docker compose up --build -d
```

**Comment by rocky4546** [comment]
thank you cookieisland

**Comment by Nostradamus1973** [comment]
@cookieisland Thank you for those instructions, I'm going to give it a try now.

**Comment by Nostradamus1973** [comment]
Okay, so I did as you said, I changed the folders accordingly and used my username instead where applicable.
When I went to edit my docker compose I saw this:

#locast2plex:
#   image: tgorg/locast2plex
#    ports:
#      - "6077:6077"
#      - "1900:1900/udp"
#    restart: unless-stopped
#    volumes:
 #     - ./config.ini:/app/config/config.ini

As you can see, I commented them out as I didn't want any confliction. Should I have left it?
Also, once I finish what you you described, how do I start the docker?
As I said before I'm new to docker, I would prefer to bring it in natively in portainer, however if it can only be start via command line then I'm down with that too.
As for as your bash script, did you place it in /opt and add it to autostart? Or, are you running it as some sort of cron job?
Thanks again

**Comment by Nostradamus1973** [comment]
Another update, I've been pulling my hair out over this without any luck. LOL
I keep doing things over and over and changing little things and not making any progress. This is a first for me with dockers, normally I would say docker has been good to me with ease of use and simplicity, Cabernet isn't following the same prescription.

I keep getting errors:
 Deployment error
failed to deploy a stack: (root) Additional property cabernet is not allowed
Currently my docker-compose.yaml looks like this:
```
cabernet:
    build:
      context: /home/nostradamus/source/cabernet
      dockerfile: Dockerfile_tvh_crypt.alpine
    image: cabernet
    container_name: cabernet
    network_mode: host
    environment:
      - TZ="America/New_York"
      - PUID=1000
      - PGID=1000
    cpu_shares: 2048
    restart: unless-stopped
    volumes:
      - /home/nostradamus/dockers/cabernet/config/data:/app/data
      - /home/nostradamus/dockers/cabernet/config/key.txt:/root/.cabernet/key.txt
```
When I go to deploy the stack within portainer I also get an unable to map volumes if I comment-out the first line "cabernet;" and add  a ' in the beginning of the volumes and at end like this:
```
volumes:
      - '/home/nostradamus/dockers/cabernet/config/data:/app/data'
      - '/home/nostradamus/dockers/cabernet/config/key.txt:/root/.cabernet/key.txt'
     
```
Thanks agfain for all your help.

**Comment by Nostradamus1973** [comment]
Would anyone be able to help me via Discord or Telegram? 
I figured real-time is always better to get things working. Especially because I'm really excited to get rolling on this app.
Thx

**Comment by cookieisland** [comment]
Since my docker-compose uses "network:host" there is no need to expose the ports.   It is good you commented out the locast2plex stuff. Locast does not exist anymore so that part of you docker-compose.yaml file is of no use.  Also I only provided you with an excerpt of the docker-compose.yaml file. I assumed you had the other nessessary stuff.  Yours should look something like this:

```
version: '2.4'
services:
  cabernet:
    build:
      context: /home/nostradamus/source/cabernet
      dockerfile: Dockerfile_tvh_crypt.alpine
    image: cabernet
    container_name: cabernet
    network_mode: host
    environment:
      - TZ="America/New_York"
      - PUID=1000
      - PGID=1000
    cpu_shares: 2048
    restart: unless-stopped
    volumes:
      - /home/nostradamus/dockers/cabernet/config/data:/app/data
      - /home/nostradamus/dockers/cabernet/config/key.txt:/root/.cabernet/key.txt
```

Since the bash script is run on demand I put it in my home directory and only run it when I want to update cabernet to the latest version.  

To start the docker container you just need to cd to the directory where you have your docker-compose.yaml file, which in my case is /home/cookieisland/compose/htpc, and then issue the following command:
`docker compose up -d`

Alternativelyu If you need to rebuild the container then use this command (it will take soem time to buid the container):
`docker compose up --buiild -d`

I don't use portainer much so I can't help you there.

**Comment by rocky4546** [comment]
Is there a docker-compose  that we should have in the repo.  I agree the locast stuff is outdated.

**Comment by cookieisland** [comment]
That makes sense @rocky4546  

Lets hear from @Nostradamus1973 to see if the latest one I posted worked for him and if so that or a variant of it can be posted.....  Maybe I can add some comments/instructions to it similar to the messages I sent previously. But lets see if he was able to get it working first.

**Comment by Nostradamus1973** [comment]
Good morning Everyone,

So, I managed to change the docker compose file and Viola, it's running!
But, now that it's running, I can't visit localhost:6077 to access the webserver.
Should there be something like this in my yaml file?:

```
ports:
      - "5004:5004"    # Port used to stream
      - "6077:6077"    # Web Interface Port
      - "65001:65001"  # HDHomeRun Port 
```
Thank you for all your help and time.

**Comment by rocky4546** [comment]
The 1900 and 65001 ports are really not needed.  65001 is the UDP port for HDHomerun devices, but most media server either have not implemented it or is not implemented correctly.  So, that port is basically not needed.  The 1900 port is for SSDP, which provides the DLNA interface.  SSDP is implemented, but DLNA not quite there.  The plan is to get DLNA available for cabernet so we can push video to other devices, but not for now.  Both are enabled/disabled in the client settings, but probably not see a need to enable at this time.  I would keep the 6077 and 5004 ports only.

**Comment by Nostradamus1973** [comment]
@rocky4546 Thx for the info.
I changed my docker compose to this:
```
version: '2.4'
services:
  cabernet:
    build:
      context: /home/nostradamus/source/cabernet
      dockerfile: Dockerfile_tvh_crypt.alpine
    image: cabernet
    ports:
      - "5004:5004"    # Port used to stream
      - "6077:6077"    # Web Interface Port
    container_name: cabernet
    network_mode: host
    environment:
      - TZ="America/New_York"
      - PUID=1000
      - PGID=1000
    cpu_shares: 2048
    restart: unless-stopped
    volumes:
      - /home/nostradamus/dockers/cabernet/config/data:/app/data
      - /home/nostradamus/dockers/cabernet/config/key.txt:/root/.cabernet/key.txt
```
   Unfortunately I still can't see any published ports. 

```
nostradamus@xxxxxx:~$ docker logs cabernet

> eplustv@2.0.8 start
> ts-node index.ts

=== E+TV v2.0.8 starting ===
== ESPN+ Auth ==
Please open a browser window and go to: https://www.espn.com/watch/activate
Enter code:  XLMSBN


```
[And here is a screenshot of Portainer running cabernet](https://ibb.co/grj8JVp):

**Comment by rocky4546** [comment]
Note: I will be pushing out a 0.9.12.0 today.  It will move all plugins to plugin_ext.  You may want to keep working with 0.9.11.* until you get things up and running.

**Comment by Nostradamus1973** [comment]
@cookieisland I removed the  'network_mode:host" statement from my yaml file. 
Here is the output:
nostradamus@xxxxxxxxxx:~$ ls -al /home/nostradamus/source/cabernet
total 96
drwxrwxr-x  8 nostradamus nostradamus 4096 Apr  2 11:43 .
drwxrwxr-x  4 nostradamus nostradamus 4096 Apr  2 11:43 ..
drwxrwxr-x  3 nostradamus nostradamus 4096 Apr  2 11:43 build
-rw-rw-r--  1 nostradamus nostradamus 4146 Apr  2 11:43 CHANGELOG.md
-rw-rw-r--  1 nostradamus nostradamus 1554 Apr  2 11:43 CONTRIBUTING.md
-rw-rw-r--  1 nostradamus nostradamus  182 Apr  2 11:43 docker-compose.yml
-rw-rw-r--  1 nostradamus nostradamus  381 Apr  2 11:43 Dockerfile
-rw-rw-r--  1 nostradamus nostradamus  364 Apr  2 11:43 Dockerfile_l2p
-rw-rw-r--  1 nostradamus nostradamus  364 Apr  2 11:43 Dockerfile_tvh
-rw-rw-r--  1 nostradamus nostradamus  631 Apr  2 11:43 Dockerfile_tvh_crypt.alpine
-rw-rw-r--  1 nostradamus nostradamus  883 Apr  2 11:43 Dockerfile_tvh_crypt.slim-buster
-rw-rw-r--  1 nostradamus nostradamus  324 Apr  2 11:43 .dockerignore
drwxrwxr-x  8 nostradamus nostradamus 4096 Apr  2 11:43 .git
drwxrwxr-x  3 nostradamus nostradamus 4096 Apr  2 11:43 .github
-rw-rw-r--  1 nostradamus nostradamus  428 Apr  2 11:43 .gitignore
drwxrwxr-x 15 nostradamus nostradamus 4096 Apr  2 11:43 lib
-rw-rw-r--  1 nostradamus nostradamus 1097 Apr  2 11:43 LICENSE
drwxrwxr-x  6 nostradamus nostradamus 4096 Apr  2 11:43 plugins
drwxrwxr-x  2 nostradamus nostradamus 4096 Apr  2 11:43 plugins_ext
-rw-rw-r--  1 nostradamus nostradamus 1597 Apr  2 11:43 README.md
-rw-rw-r--  1 nostradamus nostradamus   33 Apr  2 11:43 requirements.txt
-rw-rw-r--  1 nostradamus nostradamus 2961 Apr  2 11:43 TVHEADEND.md
-rw-rw-r--  1 nostradamus nostradamus 1794 Apr  2 11:43 tvh_main.py

Thank you

**Comment by cookieisland** [comment]
The directory looks good. However your docker cabernet container is running EPlusTV and not cabernet.  I recommend that you delete your current cabernet container and images.   I suspect you can do that via portainer but I will give you some command lines to clean things up.  

These two commands should stop cabernet and then delete all stopped containers, images, etc.  The bad thing is if you have other stopped docker containers it will delete them too and you may have to recreate them.

```
docker compose stop cabernet
docker system prune -af
```

After you run these commands then go and check portainer.  You should see that all cabernet containers and images have all be deleted.

Once you have deleted all the cabernet containers, images, etc you should recreate your cabernet container and restart it.
`docker compose up --build -d`

Hopefully when cabernet starts it will be cabernet and not EPlusTV.

**Comment by cookieisland** [comment]
once you get cabernet started please send the outpu of the following command:
`docker logs cabernet`

I can talk via discord as well if you give me your id.

**Comment by Nostradamus1973** [comment]
Hi @cookieisland 
I did as you said and completely removed it, unfortunately I can't get it to start and I have to run out and do some family stuff right now and won't be back till late.

Here's my discord handle: Nostradamus#9005 I should be available throughout the day tomorrow.
Thanks a bunch for helping me out.

**Comment by cookieisland** [comment]
ok - i sent you a friend request on discord. we can chat tomorrow

**Comment by rocky4546** [comment]
Well that makes things simpler.  thanks for looking into this.  I will update the yml file, but I suspect a header needs to be added as a comment (if possible) to explain how to setup and use.

**Comment by cookieisland** [comment]
I will test for a few days and see if things work well.  I am hoping that even if you make an update to ghcr.io/cabernetwork/cabernet:latest my new docker-compose.yaml will override it and wait for me to update cabernet via cabernet's update process.

**Comment by cookieisland** [comment]
I think yml or yaml are both valid names.

**Comment by cookieisland** [comment]
Found an error in my docker-compose.yaml file.  Timezone was not being set.  I should not have quoted TZ.  This should fix it.  I will keep testing as well.

```
version: '2.4'
services:
  cabernet:
    container_name: cabernet
    image: ghcr.io/cabernetwork/cabernet:latest
    environment:
      - TZ=America/Los_Angeles
      - PUID=1000
      - PGID=1000
    ports:
      - "6077:6077"
      - "5004:5004"
    restart: unless-stopped
    volumes:
      - /home/cookieisland/docker/cabernet/config/app:/app
      - /home/cookieisland/docker/cabernet/config/key.txt:/root/.cabernet/key.txt
```
